import { Quicksand } from 'next/font/google'
import './globals.css'

const quicksand = Quicksand({ subsets: ['latin'], weight: ['300','400','500', '600', '700'] })

export const metadata = {
  title: 'Create Austea  App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={quicksand.className}>
        <main className="max-w-7xl mx-auto border p-5">
          {children}
        </main>
      </body>
    </html>
  )
}
